### PR TITLE
better world gen (untested)

### PR DESCRIPTION
**Pull request by Syn9673**
This will provide a much better world gen, as seen in the image below.
world

### CODE REVIEW

**Comment by atomiclucky** [comment]
kinda too much rocks on the bottom

**Comment by Syn9673** [comment]
this commit should lessen it
world

**Comment by ArdaKurucim** [comment]
Rocks must be above of the lavas some of them are under of lavas

**Comment by ipr0gr4mipas2** [comment]
@realwry The rocks do spawn under lava.

**Comment by ipr0gr4mipas2** [comment]
Always test your PRs before sending pull requests

**Pull request closed without merging**
